/**
 * Client-side Markdown generation for the Phase 10 validation report.
 *
 * Composes a Markdown document purely from existing persisted data. No AI call,
 * no new information, no fake results. Sections are only emitted when the
 * underlying data actually exists.
 */

function escapeText(value) {
  if (!value) return ''
  return String(value).replace(/\r?\n/g, ' ').trim()
}

function refLabels(analysis, ids) {
  const map = new Map()
  ;(analysis.assumptions || []).forEach((a, i) =>
    map.set(`assumption-${i + 1}`, `Assumption: ${a.assumption}`),
  )
  ;(analysis.risks || []).forEach((r, i) =>
    map.set(`risk-${i + 1}`, `Risk: ${r.risk}`),
  )
  return (ids || [])
    .map((id) => map.get(id))
    .filter(Boolean)
    .map((label) => `- ${label}`)
    .join('\n')
}

function lines(push, arr) {
  arr.forEach((l) => push(l))
}

export function buildReportMarkdown(data) {
  const { idea, analysis, experiments = [] } = data
  const out = []
  const push = (s) => out.push(s)

  push(`# ${escapeText(idea.title)}`)
  push('')
  push(
    '_This report was generated by IdeaProof AI from your saved analysis. It is an AI assessment based only on the information you provided — not verified market research and not a guarantee of success._',
  )
  push('')

  // Idea Overview
  push('## Idea Overview')
  push('')
  lines(push, [
    `- **Title:** ${escapeText(idea.title)}`,
    idea.description ? `- **Description:** ${escapeText(idea.description)}` : null,
    idea.problem ? `- **Problem:** ${escapeText(idea.problem)}` : null,
    idea.targetUsers ? `- **Target users:** ${escapeText(idea.targetUsers)}` : null,
    data.createdAt ? `- **Created:** ${escapeText(data.createdAt)}` : null,
    data.updatedAt ? `- **Last updated:** ${escapeText(data.updatedAt)}` : null,
  ].filter(Boolean))
  push('')

  // AI Assessment Notice
  push('## AI Assessment Notice')
  push('')
  push(
    'The assessment below is AI-generated and based solely on the information provided. It is a perspective to challenge your thinking, not a statement of verified fact. You make the final call.',
  )
  push('')

  // Executive Summary
  if (analysis.summary) {
    push('## Executive Summary')
    push('')
    push(escapeText(analysis.summary))
    push('')
  }

  // Verdict
  push('## Verdict')
  push('')
  lines(push, [
    `- **Current recommendation:** ${escapeText(analysis.verdict)}`,
    typeof analysis.overallScore === 'number'
      ? `- **Overall score:** ${analysis.overallScore}/100 (AI assessment, not recalculated)`
      : null,
    typeof analysis.confidence === 'number'
      ? `- **AI confidence:** ${analysis.confidence}/100`
      : null,
  ].filter(Boolean))
  push('')

  // Category Analysis
  if (analysis.categoryScores && analysis.categoryScores.length) {
    push('## Category Analysis')
    push('')
    analysis.categoryScores.forEach((c) => {
      push(`- **${escapeText(c.category)}:** ${c.score}/100 — ${escapeText(c.explanation)}`)
    })
    push('')
  }

  // Assumptions
  if (analysis.assumptions && analysis.assumptions.length) {
    push('## Assumptions')
    push('')
    analysis.assumptions.forEach((a, i) => {
      push(`### Assumption ${i + 1}: ${escapeText(a.assumption)}`)
      push('')
      push(`- **Why it matters:** ${escapeText(a.rationale)}`)
      push('')
    })
  }

  // Risks
  if (analysis.risks && analysis.risks.length) {
    push('## Risks')
    push('')
    analysis.risks.forEach((r) => {
      push(`- **[${escapeText(r.severity)}]** ${escapeText(r.risk)}${r.note ? ` — ${escapeText(r.note)}` : ''}`)
    })
    push('')
  }

  // Validation Experiments
  if (experiments.length) {
    push('## Validation Experiments')
    push('')
    push(
      '_These are proposed experiments to run. They are not results — none have been conducted by the AI. A "Done" status only means you marked the experiment as done._',
    )
    push('')
    experiments.forEach((e, i) => {
      if (e.isPhase8) {
        push(`### Experiment ${i + 1}: ${escapeText(e.hypothesis)}`)
        push('')
        lines(push, [
          `- **Method:** ${escapeText(e.method)}`,
          `- **Proposed success criteria:** ${escapeText(e.successCriteria)}`,
          `- **Effort:** ${escapeText(e.effort)}`,
          `- **Timeline:** ${escapeText(e.timeline)}`,
          e.status ? `- **Status:** ${escapeText(e.status)}` : null,
        ].filter(Boolean))
        const linked = refLabels(analysis, e.assumptionIds)
        if (linked) {
          push('- **Tests:**')
          push(linked)
        }
      } else {
        push(`### Experiment ${i + 1}: ${escapeText(e.title)}`)
        push('')
        lines(push, [
          `- **Proposed success criteria:** ${escapeText(e.successCriteria)}`,
          `- **Timeline:** ${escapeText(e.timeline)}`,
        ].filter(Boolean))
      }
      push('')
    })
  }

  return out.join('\n')
}
